name: Validate Infrastructure

on:
  push:
    branches: [main, develop]
    paths:
      - "infra/terraform/**"
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./infra/terraform
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ./infra/terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./infra/terraform

  kubernetes:
    name: Kubernetes Manifest Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.27.3"

      - name: Validate Kubernetes manifests
        run: |
          find ./kubernetes -name "*.yaml" -o -name "*.yml" | xargs -I {} kubectl --dry-run=client -f {} validate
